# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 830b42260f42757122d94ca692ab8d0946b9c964159b203d3fec15a4102811de1e4840889c4d851594b3173c526d0c3a14f921e71b23cf3fd2c29645ea4be04d

test:
  secret_key_base: ca9fd27bc3769af62788acb4564e72ca5e850cc3b9fc60e635fe4cd7d76907c9e86e1a780e42c611eae62475bef2f6c3a34aaf92bc8808458a14e07688bf99b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
